### ISSUE TITLE
Automation only works when 1 to 1

### ISSUE THREAD

**Issue by rubrical-worker** [maxxnino/VerseGameTutorials#1]
The automation in your latest version only works when you have one guard per device. Maybe that is what you intended?

**Comment by maxxnino** [comment]
> The automation in your latest version only works when you have one guard per device. Maybe that is what you intended?

I actually explained that at the end of part 2. Feel free to check it out for the reasoning behind it.

**Comment by rubrical-worker** [comment]
Thanks for the reply! So many videos out there, so little time. I jumped to your code too quickly, I guess.

**Comment by maxxnino** [comment]
> Thanks for the reply! So many videos out there, so little time. I jumped to your code too quickly, I guess.

Don't worry, my friend! I've already finished part 3. Just a little work left on the thumbnail, and the video will be out soon

**Comment by maxxnino** [comment]
Done in part 3
